"""Compatibility exports for the shared land-registry API schemas.

The SQLModel schema definitions are owned by ``aecs4u-domain``. This module
keeps the historical ``land_registry.models`` import path available to the
application and its consumers.
"""

from aecs4u_domain.real_estate.land_registry_schemas import (
    CacheMetadata,
    CadastralCacheInfoResponse,
    CadastralLookupItem,
    CadastralLookupResponse,
    CadastralStatistics,
    ComuniSearchResponse,
    DataBlock,
    EnrichmentDatasetStatus,
    ErrorResponse,
    FileAvailabilityStats,
    FreshnessMetadata,
    GeoJSONFeature,
    GeoJSONFeatureCollection,
    HealthResponse,
    IngestionManifest,
    LineageMetadata,
    MicrozoneBulkVisibilityRequest,
    MicrozoneCreateRequest,
    MicrozoneDetailResponse,
    MicrozoneListResponse,
    MicrozoneResponse,
    MicrozoneUpdateRequest,
    SavedParcelCollectionResponse,
    SavedParcelCreateRequest,
    SavedParcelResponse,
    SavedParcelUpdateRequest,
    ServiceUnavailableResponse,
    TableDataResponse,
    ZoneBulkVisibilityRequest,
    ZoneCreateRequest,
    ZoneDetailResponse,
    ZoneListResponse,
    ZoneResponse,
    ZoneUpdateRequest,
)
from aecs4u_domain.real_estate.models import ParcelIdentity, ParcelVersion

__all__ = [
    "CacheMetadata",
    "CadastralCacheInfoResponse",
    "CadastralLookupItem",
    "CadastralLookupResponse",
    "CadastralStatistics",
    "ComuniSearchResponse",
    "DataBlock",
    "EnrichmentDatasetStatus",
    "ErrorResponse",
    "FileAvailabilityStats",
    "FreshnessMetadata",
    "GeoJSONFeature",
    "GeoJSONFeatureCollection",
    "HealthResponse",
    "IngestionManifest",
    "LineageMetadata",
    "MicrozoneBulkVisibilityRequest",
    "MicrozoneCreateRequest",
    "MicrozoneDetailResponse",
    "MicrozoneListResponse",
    "MicrozoneResponse",
    "MicrozoneUpdateRequest",
    "ParcelIdentity",
    "ParcelVersion",
    "SavedParcelCollectionResponse",
    "SavedParcelCreateRequest",
    "SavedParcelResponse",
    "SavedParcelUpdateRequest",
    "ServiceUnavailableResponse",
    "TableDataResponse",
    "ZoneBulkVisibilityRequest",
    "ZoneCreateRequest",
    "ZoneDetailResponse",
    "ZoneListResponse",
    "ZoneResponse",
    "ZoneUpdateRequest",
]
